spring:
  application:
     name: zuul-server

server:
  port: 9000

logging:
    file: logs/zuul-server.log

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  prefix: /api
  ignoredServices: '*'
  routes:
    user-service:
      path: /user-service/**
      serviceId: USER-SERVICE
    task-service:
      path: /task-service/**
      serviceId: TASK-SERVICE
    report-service:
      path: /report-service/**
      serviceId: REPORT-SERVICE