spring:
  application:
     name: user-service

server:
  port: 9110

logging:
    file: logs/user-service.log

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

endpoints:
  shutdown:
    enabled: true